spring:
  application:
    name: "Gateway Service"

  messages:
    basename: message
    encoding: UTF-8

  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:8081
          predicates:
            - name: Path
              args:
                pattern: /inventory/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - name: Path
              args:
                pattern: /users/**

server:
  port: 8080
