openapi: 3.0.1
info:
  title: Inventory Service API
  description: API for managing home inventory
  version: v1
servers:
  - url: http://localhost:5050/api
    description: Local Development Server
paths:
  /v1/categories:
    $ref: './Category/endpoint.yaml#/%2Fv1%2Fcategories'
  /v1/category:
    $ref: './Category/endpoint.yaml#/%2Fv1%2Fcategory'
  /v1/category/{categoryId}:
    $ref: './Category/endpoint.yaml#/%2Fv1%2Fcategory%2F{categoryId}'

  /v1/items:
    $ref: './Item/endpoint.yaml#/%2Fv1%2Fitems'
  /v1/item:
    $ref: './Item/endpoint.yaml#/%2Fv1%2Fitem'
  /v1/item/{itemId}:
    $ref: './Item/endpoint.yaml#/%2Fv1%2Fitem%2F{itemId}'



  /v1/compartments:
    $ref: './Compartment/endpoint.yaml#/%2Fv1%2Fcompartments'
  /v1/compartment/{compartmentId}:
    $ref: './Compartment/endpoint.yaml#/%2Fv1%2Fcompartment%2F{compartmentId}'

  /v1/locations:
    $ref: './Location/endpoint.yaml#/%2Fv1%2Flocations'
  /v1/location/{locationId}:
    $ref: './Location/endpoint.yaml#/%2Fv1%2Flocation%2F{locationId}'

  /v1/storageunits:
    $ref: './StorageUnit/endpoint.yaml#/%2Fv1%2Fstorageunits'
  /v1/storageunit/{storageUnitId}:
    $ref: './StorageUnit/endpoint.yaml#/%2Fv1%2Fstorageunit%2F{storageUnitId}'