openapi: 3.0.1
info:
  title: Inventory Service API
  description: API for managing home inventory
  version: v1
servers:
  - url: http://localhost:5050/api
    description: Local Development Server
paths:
  /v1/categories:
    $ref: './endpoint/Category.yaml#/%2Fv1%2Fcategories'
  /v1/category/{categoryId}:
    $ref: './endpoint/Category.yaml#/%2Fv1%2Fcategory%2F{categoryId}'

  /v1/items:
    $ref: './endpoint/Item.yaml#/%2Fv1%2Fitems'
  /v1/item/{itemId}:
    $ref: './endpoint/Item.yaml#/%2Fv1%2Fitem%2F{itemId}'

  /v1/compartments:
    $ref: './endpoint/Compartment.yaml#/%2Fv1%2Fcompartments'
  /v1/compartment/{compartmentId}:
    $ref: './endpoint/Compartment.yaml#/%2Fv1%2Fcompartment%2F{compartmentId}'

  /v1/locations:
    $ref: './endpoint/Location.yaml#/%2Fv1%2Flocations'
  /v1/location/{locationId}:
    $ref: './endpoint/Location.yaml#/%2Fv1%2Flocation%2F{locationId}'

  /v1/storage-units: # Corrected path to use hyphen
    $ref: './endpoint/StorageUnit.yaml#/%2Fv1%2Fstorage-units' # Corrected $ref path and fragment
  /v1/storage-unit/{storageUnitId}: # Corrected path to use hyphen
    $ref: './endpoint/StorageUnit.yaml#/%2Fv1%2Fstorage-unit%2F{storageUnitId}' # Corrected $ref path and fragment