spring:
  application:
    name: "Inventory Service"

  messages:
    basename: message
    encoding: UTF-8

  datasource:
    credentialsPath: "classpath:/postgresql/default_credentials.json"
    hikari:
      jdbcUrl: jdbc:postgresql://localhost:15432/inventory_service
      connectionTimeout: 20000
      minimumIdle: 5
      maximumPoolSize: 15
      idleTimeout: 120000
      connection-test-query: SELECT 1

  jpa:
    open-in-view: false

  liquibase:
    liquibase-schema: public
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: UTC
